language: ruby

rvm:
 - 2.4

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install 8
  - node -v
  - npm i -g yarn
  - yarn install

script:
  - bundle exec rake
  - yarn lint

notifications:
  email:
    on_success: never
    on_failure: always
